# Generated by Django 5.2.13 on 2026-04-13 20:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin_number', models.CharField(blank=True, max_length=64, verbose_name='CIN Number')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Back-Office',
                'verbose_name_plural': 'Back-Office',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(blank=True, help_text='Official identity card number.', max_length=128, verbose_name='ID Card')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_en', models.CharField(max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('applies_to_loan_types', models.JSONField(default=list, help_text='List of loan type codes, e.g. ["personal", "business"].')),
                ('is_required', models.BooleanField(default=True)),
                ('min_files', models.PositiveIntegerField(default=1, help_text='Minimum uploads linked to this requirement (e.g. 3 payslips).')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Document Requirement',
                'verbose_name_plural': 'Document Requirements',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='eligibility_kb/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='File (pdf)')),
                ('manual_text', models.TextField(blank=True, help_text='Optional: paste rules here if automatic extraction from the file fails.')),
                ('extracted_text', models.TextField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Eligibility Condition',
                'verbose_name_plural': 'Eligibility Conditions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.TextField(blank=True, help_text='Used for chat, RAG extraction, and document vision. You can also set OPENAI_API_KEY in the environment (it takes precedence).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration settings (OpenAI)',
                'verbose_name_plural': 'Integration settings (OpenAI)',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('email_verified', models.BooleanField(default=False)),
                ('account_type', models.CharField(choices=[('customer', 'Customer'), ('backoffice', 'Back-Office')], db_index=True, default='customer', help_text='Customer: own loan requests only. Back-Office: manage all requests.', max_length=20, verbose_name='Type')),
                ('preferred_language', models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='fr', max_length=5)),
                ('theme_preference', models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('back_office', models.OneToOneField(blank=True, help_text='Linked Back-Office profile (set when Type = Back-Office).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='core.backoffice', verbose_name='BackOfficeId')),
                ('customer', models.OneToOneField(blank=True, help_text='Linked Customer profile (set when Type = Customer).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='core.customer', verbose_name='CustomerId')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('code', models.CharField(blank=True, db_index=True, default='', help_text='Numeric code sent by email (empty for legacy rows).', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('loan_type', models.CharField(choices=[('personal', 'Personal loan'), ('mortgage', 'Mortgage'), ('business', 'Business loan')], default='personal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('closed', 'Closed')], default='pending', max_length=20, verbose_name='Status')),
                ('language', models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='fr', help_text='Language for this request (UI + AI agents).', max_length=5)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('due_date', models.DateField(blank=True, help_text='Deadline or offer expiry date.', null=True, verbose_name='Due Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('score', models.FloatField(blank=True, help_text='Eligibility score computed by the AI model (0.0 to 1.0).', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Score')),
                ('amount_requested', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('term_months', models.PositiveIntegerField(default=12)),
                ('annual_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('purpose', models.TextField(blank=True)),
                ('current_step', models.CharField(default='welcome', max_length=64)),
                ('face_verification', models.JSONField(blank=True, default=dict)),
                ('liveness_verification', models.JSONField(blank=True, default=dict, help_text='Liveness video analysis: head turns, face match vs ID, debug payloads.')),
                ('roi_summary', models.JSONField(blank=True, default=dict)),
                ('business_impact', models.JSONField(blank=True, default=dict)),
                ('orchestration_log', models.JSONField(blank=True, default=list)),
                ('final_report_html', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(help_text='Login account (Account) that submitted this request.', on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL, verbose_name='Account')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to='core.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Loan Request',
                'verbose_name_plural': 'Loan Requests',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', 'ID Card'), ('pay_stub', 'PayStub'), ('tax_return', 'TaxReturn'), ('face_selfie', 'Face selfie'), ('liveness_video', 'Liveness video'), ('other', 'Other')], default='id_card', help_text='Nature of the document (ERD: Type picklist).', max_length=32, verbose_name='Type')),
                ('file', models.FileField(blank=True, help_text='Binary file or path to cloud storage (ERD: File).', null=True, upload_to='documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='File')),
                ('validation_rule', models.TextField(blank=True, help_text="Compliance rule applied to this document (e.g. 'Less than 3 months old').", verbose_name='Validation Rule')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('sha256_hex', models.CharField(blank=True, db_index=True, max_length=64)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('storage_path', models.CharField(blank=True, max_length=512)),
                ('analysis_result', models.JSONField(blank=True, default=dict)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='core.documentrequirement')),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.loanrequest', verbose_name='LoanRequestId')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('step_hint', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='core.loanrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Moment the alert was sent.', verbose_name='Date')),
                ('read', models.BooleanField(default=False, help_text='Whether the notification has been read (True/False).', verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='core.loanrequest', verbose_name='LoanRequestId')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['account', '-creation_date'], name='core_loanre_account_3f8fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['customer', '-creation_date'], name='core_loanre_custome_d4042d_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['reference'], name='core_loanre_referen_713162_idx'),
        ),
    ]
