# Generated by Django 5.2.13 on 2026-04-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Numeric code sent by email (empty for legacy rows).', max_length=12),
        ),
    ]
