# Generated by Django 5.2.13 on 2026-04-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_email_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='liveness_verification',
            field=models.JSONField(blank=True, default=dict, help_text='Liveness video analysis: head turns, face match vs ID, debug payloads.'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='kind',
            field=models.CharField(choices=[('generic', 'Generic'), ('identity', 'Identity'), ('income', 'Income proof'), ('face_selfie', 'Face selfie'), ('liveness_video', 'Liveness video')], default='generic', max_length=32),
        ),
    ]
