# Generated by Django 5.2.13 on 2026-04-12 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_liveness_verification_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityKnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='eligibility_kb/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp'])])),
                ('manual_text', models.TextField(blank=True, help_text='Optional: paste rules here if automatic extraction from the file fails.')),
                ('extracted_text', models.TextField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'eligibility knowledge source',
                'verbose_name_plural': 'eligibility knowledge sources',
                'ordering': ['-created_at'],
            },
        ),
    ]
