# Generated by Django 5.2.13 on 2026-04-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_eligibility_knowledge_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.TextField(blank=True, help_text='Used for chat, RAG extraction, and document vision. You can also set OPENAI_API_KEY in the environment (it takes precedence).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration settings (OpenAI)',
                'verbose_name_plural': 'Integration settings (OpenAI)',
            },
        ),
    ]
