# Generated by Django 5.2.13 on 2026-04-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_integration_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portal_role',
            field=models.CharField(choices=[('customer', 'Customer'), ('backoffice', 'Backoffice')], db_index=True, default='customer', help_text='Customer: own applications only. Backoffice: list and open all applications.', max_length=20),
        ),
    ]
