# Generated by Django 5.2.13 on 2026-04-12 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_erd_data(apps, schema_editor):
    User = apps.get_model("core", "User")
    Customer = apps.get_model("core", "Customer")
    BackOffice = apps.get_model("core", "BackOffice")
    LoanApplication = apps.get_model("core", "LoanApplication")

    status_map = {"draft": "pending", "approved": "validated", "completed": "closed"}
    for la in LoanApplication.objects.all():
        new_status = status_map.get(la.status)
        if new_status:
            la.status = new_status
            la.save(update_fields=["status"])

    for user in User.objects.all():
        role = getattr(user, "portal_role", None) or "customer"
        if role == "backoffice":
            BackOffice.objects.get_or_create(
                user_id=user.pk,
                defaults={
                    "email": (user.email or "")[:254],
                    "first_name": user.first_name or "",
                    "last_name": user.last_name or "",
                },
            )
        else:
            Customer.objects.get_or_create(
                user_id=user.pk,
                defaults={
                    "email": (user.email or "")[:254],
                    "first_name": user.first_name or "",
                    "last_name": user.last_name or "",
                },
            )

    for la in LoanApplication.objects.all():
        if la.customer_id or not la.user_id:
            continue
        user = User.objects.filter(pk=la.user_id).first()
        if not user:
            continue
        c, _ = Customer.objects.get_or_create(
            user_id=user.pk,
            defaults={
                "email": (user.email or "")[:254],
                "first_name": user.first_name or "",
                "last_name": user.last_name or "",
            },
        )
        la.customer_id = c.pk
        la.save(update_fields=["customer_id"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_portal_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='eligibilityknowledgesource',
            options={'ordering': ['-created_at'], 'verbose_name': 'Eligibility condition', 'verbose_name_plural': 'Eligibility conditions'},
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='validation_rule',
            field=models.TextField(blank=True, help_text='Optional rule text or validator id for this document type (ERD).'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='due_date',
            field=models.DateField(blank=True, help_text='Optional target decision or offer expiry date (ERD).', null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('under_review', 'Under review'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='user',
            field=models.ForeignKey(help_text='Account (login user); same as customer.user when set.', on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BackOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin_number', models.CharField(blank=True, max_length=64)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backoffice_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Back-Office',
                'verbose_name_plural': 'Back-Office',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(blank=True, help_text='National ID / CIN / ID card number.', max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, help_text='Profile copy; canonical login email is on Account (User).', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to='core.customer'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['customer', '-created_at'], name='core_loanap_custome_697d8c_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.loanapplication'),
        ),
        migrations.RunPython(forwards_erd_data, noop_reverse),
    ]
