# Generated by Django 5.2.13 on 2026-04-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_facial_recognition'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequirement',
            name='min_files',
            field=models.PositiveIntegerField(default=1, help_text='Minimum uploads linked to this requirement (e.g. 3 payslips).'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='kind',
            field=models.CharField(choices=[('generic', 'Generic'), ('identity', 'Identity'), ('income', 'Income proof'), ('address', 'Proof of address')], default='generic', max_length=32),
        ),
    ]
