# Generated by Django 5.2.13 on 2026-04-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customer_country_currency_payslip_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequirement',
            name='payslip_distinct_months_window',
            field=models.PositiveSmallIntegerField(blank=True, help_text='If set (e.g. 3), payslips must cover that many distinct calendar months within the recent window (see policy / RAG). Null = do not validate dates.', null=True),
        ),
    ]
