# Generated by Django 5.2.13 on 2026-04-13 11:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customer_country_currency_and_payslip_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Optional manual annual income; otherwise estimated from payslip analysis (same currency as income_currency).', max_digits=14),
        ),
    ]
