# Generated by Django 5.2.13 on 2026-04-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_user_soft_delete_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
