# Generated by Django 5.2.13 on 2026-04-14 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantGuideSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('backoffice', 'Backoffice'), ('admin', 'Admin'), ('any', 'All roles')], default='any', help_text='User role this guide applies to.', max_length=20, verbose_name='Role')),
                ('page_context', models.CharField(choices=[('home', 'Home'), ('dashboard', 'Customer dashboard'), ('application_detail', 'Application detail'), ('backoffice_dashboard', 'Backoffice dashboard'), ('any', 'All pages')], default='any', help_text='Page/section where this guide is injected.', max_length=40, verbose_name='Page')),
                ('title', models.CharField(max_length=200)),
                ('source_file', models.FileField(blank=True, help_text='Upload a PDF, TXT or MD file. Text is extracted automatically.', upload_to='assistant_guides/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'md'])])),
                ('extracted_text', models.TextField(blank=True, editable=False, help_text='Auto-extracted from the uploaded file.')),
                ('manual_text', models.TextField(blank=True, help_text='Optional: type or paste the guide content directly here.')),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assistant guide',
                'verbose_name_plural': 'Assistant guides',
                'ordering': ['role', 'page_context'],
            },
        ),
    ]
