# Generated by Django 5.2.13 on 2026-04-15 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_assistant_guide_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='eligibility_override',
            field=models.BooleanField(blank=True, help_text='Manual eligibility decision by backoffice/admin. None = AI decision, True = force eligible, False = force rejected.', null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='eligibility_override_at',
            field=models.DateTimeField(blank=True, help_text='When the manual override was applied.', null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='eligibility_override_by',
            field=models.ForeignKey(blank=True, help_text='User who applied the manual override.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='eligibility_override_note',
            field=models.TextField(blank=True, help_text='Optional reason or comment for the override.'),
        ),
    ]
